kanban_todo/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('todo.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

todo/urls.py
from django.urls import path
from .views import *


urlpatterns = [
    path('', index, name='index'),
    path('add_column/', addColumn, name='add_column'),
    path('add_todo/<str:column>/', addTodo, name='add_todo'),
    path('add_todo/', addTodo, name='add_todo'),
    # path('redirect/<str:link>/', link_redirect, name='link_redirect'),
]

todo/models.py
from django.db import models

'''
    This is the model for Column
    It has 3 atttributes which are:
        1. title: used to specify the title
        2. icon: used to specify which material-icon is used when the column is displayed
        3. pallette: used to specify the type of color bar the column has when displayed (also uses material-pallette)
'''
class Column (models.Model):
    title = models.CharField(max_length=20)
    icon = models.CharField(max_length=20, blank=True, default="filter_none")
    palette = models.CharField(max_length=20, blank=True, default="kanban To-do")

    def __str__(self):
        return self.title


'''
    This is the model for Todo
    It has 6 attributes which are:
        1. title: used to specify the title of the todo
        2. description: used to specify the description of the todo
        3. column: used to specify to which column object the todo instance belongs to (Foriegn Key)
        4. pallette: used to specify the color bar of the todo when displayed (uses material)
        5. link: used to store the external link which corresponds to the todo
        6. attachement: used to specify the file associated with the todo 
'''
class Todo(models.Model):
    title = models.CharField(max_length=20)
    description = models.CharField(max_length=500)
    column = models.ForeignKey(Column, on_delete=models.CASCADE)
    palette = models.CharField(max_length=20, blank=True)
    link = models.URLField(max_length=100, blank=True)
    attachment = models.FileField(upload_to="files", blank=True)

    def __str__(self):
        return self.title 

todo/forms.py
from django import forms
from .models import Column, Todo


'''
    This is the form for Column model
    All attributes are mentioned and required
'''
class ColumnForm(forms.ModelForm):
    title = forms.CharField(max_length=20)
    icon = forms.CharField(max_length=20, required=False)
    palette = forms.CharField(max_length=20, required=False)

    class Meta:
        model = Column
        fields = ('title', 'icon', 'palette')


'''
    This is the form for Todo model
    The column attribute is not mandatory because it will be handled and set in the view
    But other attributes are handled by this form
'''
class TodoForm(forms.ModelForm):
    title = forms.CharField(max_length=20)
    description = forms.CharField(max_length=500)
    column = forms.ModelChoiceField(queryset=Column.objects.all())
    palette = forms.CharField(max_length=20, required=False)
    link = forms.CharField(max_length=100, required=False)
    attachment = forms.FileField(required=False)

    class Meta:
        model = Todo
        fields = ('title', 'description', 'palette', 'link', 'attachment')

todo/views.py
from django.shortcuts import render, redirect
from .models import Column, Todo
from .forms import ColumnForm, TodoForm

''''
    This is the base view, it retrives the list of columns and todos ...
    from database and send it to the index.html page
'''
def index(request):
    column_list = Column.objects.all()
    todo_list = Todo.objects.all()
    context_dic = {"columns": column_list, "todos": todo_list}
    return render(request, 'todo/index.html', context_dic)


'''
    This view gets invoked from the home page (index.html)
    Obtains the data sent from the form and save it to the database
    Else it returns the form to be filled
'''
def addColumn(request):
    column_form = ColumnForm()
    print(request.POST)
    if request.method == 'POST':
        column_form = ColumnForm(request.POST)
        if column_form.is_valid():
            column_form.save(commit=True)
            return redirect('/')
        else:
            print("Add Column Unsucessfull")
            print(column_form.errors)
    return render(request, 'todo/add_column.html', {'column_form': column_form})


'''
    This view gets invoked from the home page
    It is used to add new todo to the database
    If the request is post and the form is sent, this view saves it to the database
    Else it returns the form to be filled
'''
def addTodo(request, column=None):
    todo_form = TodoForm()
    column_list = Column.objects.all()
    context_dic = {'todo_form': todo_form, "column": column}

    if request.method == 'POST':
        column = Column.objects.get(title=request.POST['column'])
        todo_post = {'title':request.POST['title'], 'description':request.POST['description'],
                                'column': column, 'palette':request.POST['palette'], 'link':request.POST['link']}
        todo_form = TodoForm(todo_post, request.FILES)
        if todo_form.is_valid():
            todo = todo_form.save(commit=False)
            todo.column = column
            todo.save(0)
            return redirect('/')
        else:
            print(todo_form.errors)
    else:
        context_dic["columns"] = column_list
    return render(request, 'todo/add_todo.html', context_dic)

# def link_redirect(request, link=None):
#     print("************")
#     print(link)
#     return redirect(link)

templates/todo/add_column.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<link rel='stylesheet' href='https://fonts.googleapis.com/icon?family=Material+Icons'>

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

    <title>Add Column</title>
</head>
<body>
<h2>  Add Column </h2>
<div class="col-sm-5 form-group-lg">
    <form id="column_form" method="POST" action="{% url 'add_column' %}">
        {% csrf_token %}
        <div class="form-group">
            <label for="id_title">Title</label>
            <input name="title" type="text" class="form-control" id="id_title" placeholder="Enter title">
        </div>     
        <div class="form-group">
            <label for="id_icon">Icon</label>
            <select id="id_icon" name="icon" class="form-control">
                <option value="" disabled selected>Choose your option</option>
                <option value="filter_none" > Default </option>
                <option value="report_problem"> Alert </option>
                <option value="build"> In progress </option>
                <option value="check_circle"> Done </option>
                <option value="delete"> Gone </option>
                <option value="announcement"> Announcement </option>
                <option value="info"> Info </option>
                <option value="view_list"> List </option>
            </select>
        </div>   
        <div class="form-group">
            <label for="id_palette">Pallete</label>
            <select id="id_palette" name="palette" class="form-control">
                <option value="" disabled selected>Choose your option</option>
                <option value="kanban To-do" > Yellow </option>
                <option value="kanban progress"> Blue </option>
                <option value="kanban  Done"> Green </option>
                <option value="kanban Gone"> Red </option>
            </select>
        </div>      
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
    
</div>


</body>

</html>

templates/todo/add_todo.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

    <title>Add Todo</title>
</head>
<body>
<h2>  Add Todo </h2>
<div class="col-sm-5 form-group-lg">
    <form id="todo_form" method="POST" action="{% url 'add_todo' %}" enctype="multipart/form-data"``>
        {% csrf_token %}
        <div class="form-group">
            <label for="id_title">Title</label>
            <input name="title" type="text" class="form-control" id="id_title" placeholder="Enter title">
        </div>     
        <div class="form-group">
            <label for="id_description">Description</label>
            <input name="description" type="text" class="form-control" id="id_description" placeholder="Enter decription">
        </div>   
        <div class="form-group">
            <label for="id_column">Column</label>
            <select id="id_column" name="column" class="form-control">
                <option value="" disabled selected>Choose your option</option>
                {% if columns %}
                    {% for one_col in columns %}
                        {% if  one_col.title == column %}
                            <option value="{{ one_col.title }}" selected="selected"> {{ one_col.title }} </option>
                        {% else  %}
                            <option value="{{ one_col.title }}" > {{ one_col.title }} </option>
                        {%  endif %}
                    {% endfor %}
                {% endif %}
            </select>

        </div>      
        <div class="form-group">
            <label for="id_palette">Pallete</label>
            <select id="id_palette" name="palette" class="form-control">
                <option value="" disabled selected>Choose your option</option>
                <option value="kanban To-do" > Yellow </option>
                <option value="kanban progress"> Blue </option>
                <option value="kanban  Done"> Green </option>
                <option value="kanban Gone"> Red </option>
            </select>
        </div>      
        <div class="form-group">
            <label for="id_link">Link</label>
            <input name="link" type="text" class="form-control" id="id_link" placeholder="Enter link">
        </div>      
        <div class="form-group">
            <label for="id_attachment">Attachment</label>
            <input name="attachment" type="file" class="form-control" id="id_attachment" placeholder="Enter attachment">
        </div>      
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
</div>
</body>

</html>

templates/todo/index.html
<!DOCTYPE html>
{% load static %}

<html lang="en" >
<head>
  <meta charset="UTF-8">
  <title>CodePen - Kanban Board</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/5.0.0/normalize.min.css">
<link rel='stylesheet' href='https://fonts.googleapis.com/icon?family=Material+Icons'>
<link rel='stylesheet' href='https://fonts.googleapis.com/css?family=Arbutus+Slab'>
<link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/spectrum/1.8.0/spectrum.min.css'>
<link rel="stylesheet" href="{% static 'style.css' %}">

</head>
<body>
    <!-- partial:index.partial.html -->
    <!-- Simple MDL Progress Bar -->
    <div id="p1" class="mdl-progress mdl-js-progress"></div>
    <script>
      document.querySelector('#p1').addEventListener('mdl-componentupgraded', function() {
        this.MaterialProgress.setProgress(44);
      });
    </script><div class="kanban__title">
          <h1><i class="material-icons">check</i> To do list</h1></div>
    <div class="dd">
      {% if columns %}
          {% for  one_col in columns %}

            <ol class= "{{ one_col.palette }}">
              <div class="kanban__title">
                <h2><i class="material-icons">{{ one_col.icon }}</i> {{ one_col.title }}</h2></div> 

                  {% if todos %}
                    {% for todo in todos%}
                      {% if todo.column == one_col %}
                        <li class="dd-item" data-id="{{todo.id}}">
                          <h3 class="title dd-handle" > <i class=" material-icons ">filter_none</i> {{ todo.title }}</h3>
                            <div class="text" contenteditable="true">{{ todo.description }}</div>
                            <!-- {% if todo.link %}
                              <a href={% url  'link_redirect' %}>Link</a>
                            {% endif %} -->
                            {% if todo.attachment %}
                              <a href="{{MEDIA_URL}}/media/{{ todo.attachment }}">Attachement</a>
                            {% endif %}
                            <div class="actions">
                              <i class="material-icons" id="color">palette</i><i class="material-icons">edit</i>
                              <i class="material-icons">insert_link</i><i class="material-icons">attach_file</i>
                            </div>
                        </li>
                      {% endif %}
                    {% endfor %}
                  {% endif %}               
               <li class="dd-item">
                <div class="actions" class="dd-item">
                  <button class="addbutt" id="{{ one_col.title }}" onclick="location.href = 'add_todo/{{ one_col.title }}'"><i class="material-icons">control_point</i> Add new</button>
                </div>
              </li>
            </ol>
          {% endfor %}
      {% else %}
        <h2> <i class="material-icons">error</i> No todos yet </h2></div>
      {% endif %}
    </div>

    <menu class="kanban"><button><i class="material-icons">settings</i></button> <button><i class="material-icons">chevron_left</i></button>
      <button class="viewkanban"><i class="material-icons ">view_column</i></button>
      <button class="viewlist"><i class="material-icons">view_list</i></button>
      <button onclick="location.href = 'add_column/'"><i class="material-icons">playlist_add</i>  Add new Column </button>
      </menu>

      

    <!-- partial -->
  <script src='https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js'></script>
  <script src='https://cdnjs.cloudflare.com/ajax/libs/spectrum/1.8.0/spectrum.min.js'></script>
  <script  src="{% static 'script.js' %}"></script>

</body>
</html>